### ISSUE TITLE
Where is the code?

### ISSUE THREAD

**Issue by rachelnertia** [mknejp/vmcontainer#1]
Just watched your excellent Meeting C++ presentation on YouTube, very interested in reading the implementation! It seems like it's supposed to be here but hasn't been pushed yet?

**Comment by mknejp** [comment]
That's right. We're still working on getting the interfaces stable (not of the container, but everything around it). We want to release it very soon.

**Comment by lie-yan** [comment]
I also watched the meeting c++ talk. Hope to see the code soon.

**Comment by gracicot** [comment]
@mknejp hey! Any update on this? Even though the implementation is not perfect, I would be glad to offer my help to make it better and more suitable to reside in a master branch.

**Comment by mknejp** [comment]
It's finally here. Sorry everyone for the long wait. This really didn't wok out as planned. `pinned_vector` itself is fully implemented but there are still tests missing and the interface of support types is still work in progress. Hopefully I will now have more time to continue working on this.
