### ISSUE TITLE
Publish current implementation under "experimental" branch

### ISSUE THREAD

**Issue by FireFlyForLife** [mknejp/vmcontainer#2]
I would be very interested in trying out the pinned_vector, and peeking into the implementation.

I know you are probably hard at work stabilizing the API, so would it be possible to publish the current implementation under a "experimental" so people know that the current API/implementation is not the final one yet?

**Comment by gracicot** [comment]
Also I'm sure we can help stabilizing the API and upgrading the code quality with you, it doesn't have to be perfect for it to be shared!

I'm very interested by this for my ECS. I have many optimisations that I could do having `pinned_vector` at my disposal!

**Comment by mknejp** [comment]
https://github.com/mknejp/vmcontainer/issues/1#issuecomment-913156403
